# Generated by Django 4.2.4 on 2023-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default=8, upload_to='album_covers/'),
            preserve_default=False,
        ),
    ]
